# Generated by Django 4.2 on 2023-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
