# Generated by Django 4.2 on 2023-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'A phone number cannot have more than 15 digits'}, max_length=15, verbose_name='phone number'),
        ),
    ]
