# Generated by Django 4.2 on 2023-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPrice',
            fields=[
                ('id', models.CharField(default='btc_price', max_length=20, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Данные о стоимости биткоина (в usd)',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashrate', models.FloatField(verbose_name='Хешрейт')),
                ('contract_start', models.DateField(verbose_name='Начало')),
                ('contract_end', models.DateField(verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.CharField(default='difficulty', max_length=20, primary_key=True, serialize=False)),
                ('difficulty', models.BigIntegerField(default=49549703178593, verbose_name='Сложность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Данные о сложности',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('id', models.CharField(default='maintenance_cost', max_length=20, primary_key=True, serialize=False)),
                ('coast', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Данные о стоимости обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.CharField(default='reward_block', max_length=20, primary_key=True, serialize=False)),
                ('reward_block', models.FloatField(default=6.81, verbose_name='Награда')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Данные о награде',
            },
        ),
    ]
