# Generated by Django 4.2 on 2023-05-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_first_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Данные о стоимости обслуживания',
            },
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'Данные о сложности'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Данные о награде'},
        ),
        migrations.AddField(
            model_name='difficulty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='reward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty',
            field=models.BigIntegerField(default=49549703178593, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_block',
            field=models.FloatField(default=6.81, verbose_name='Награда'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashrate', models.FloatField(verbose_name='Хешрейт')),
                ('contract_start', models.DateTimeField(verbose_name='Начало')),
                ('contract_end', models.DateTimeField(verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Контракты',
            },
        ),
    ]
