# Generated by Django 4.2 on 2023-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_maintenancecost_alter_difficulty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='id',
            field=models.CharField(default='difficulty', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenancecost',
            name='id',
            field=models.CharField(default='maintenance_coast', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.CharField(default='reward_block', max_length=20, primary_key=True, serialize=False),
        ),
    ]
