# Generated by Django 4.2 on 2023-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_difficulty_id_alter_maintenancecost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_end',
            field=models.DateField(verbose_name='Завершение'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_start',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='maintenancecost',
            name='id',
            field=models.CharField(default='maintenance_cost', max_length=20, primary_key=True, serialize=False),
        ),
    ]
