# Generated by Django 4.2 on 2023-07-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_contract_options_contract_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btcprice',
            options={'verbose_name': 'стоимость btc (в usd)', 'verbose_name_plural': 'Данные о стоимости биткоина (в usd)'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-created_at',), 'verbose_name': 'контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'сложность', 'verbose_name_plural': 'Данные о сложности'},
        ),
        migrations.AlterModelOptions(
            name='maintenancecost',
            options={'verbose_name': 'стоимость обслуживания', 'verbose_name_plural': 'Данные о стоимости обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'награда', 'verbose_name_plural': 'Данные о награде'},
        ),
    ]
