# Generated by Django 4.2 on 2023-05-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_contract_contract_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPrice',
            fields=[
                ('id', models.CharField(default='btc_price', max_length=20, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Данные о стоимости биткоина (в usd)',
            },
        ),
    ]
