# Generated by Django 4.2 on 2023-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_btcprice_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalThCost',
            fields=[
                ('id', models.CharField(default='th_rent_cost', max_length=20, primary_key=True, serialize=False)),
                ('coast', models.FloatField(default=0, verbose_name='Стоимость аренды')),
            ],
            options={
                'verbose_name': 'стоимость аренды 1 TH (в usd)',
                'verbose_name_plural': 'Данные о стоимость аренды 1 TH (в usd)',
            },
        ),
    ]
