# Generated by Django 4.2 on 2023-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rentalthcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalthcost',
            name='id',
            field=models.CharField(default='th_rental_cost', max_length=20, primary_key=True, serialize=False),
        ),
    ]
