# Generated by Django 4.2 on 2023-07-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_rentalthcost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancecost',
            old_name='coast',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='rentalthcost',
            old_name='coast',
            new_name='cost',
        ),
    ]
