# Generated by Django 4.2 on 2023-07-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_coast_maintenancecost_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyToUsdtExchange',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usdt', models.FloatField(default=0, verbose_name='Цена в usdt')),
            ],
            options={
                'verbose_name': 'курс криптовалюты (в usd)',
                'verbose_name_plural': 'Данные о курсах криптовалют (в usd)',
            },
        ),
    ]
