# Generated by Django 4.2 on 2023-07-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_cryptocurrencytousdtexchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BtcPrice',
        ),
    ]
